---
- ansible.builtin.import_playbook: starfive-visionfive2-create-boot-compile-ubuntu-24-10.yaml

- hosts: localhost
  vars:
    u_boot: "{{ starfive_visionfive2_u_boot_ubuntu_24_10 }}"
    release_dir: ubuntu-24-10
  tasks:
    - include_tasks: tasks/create-release.yaml

- ansible.builtin.import_playbook: starfive-visionfive2-create-boot-compile-fedora-41.yaml

- hosts: localhost
  vars:
    u_boot: "{{ starfive_visionfive2_u_boot_fedora_41 }}"
    release_dir: fedora-41
  tasks:
    - include_tasks: tasks/create-release.yaml

    - name: Compress directory
      community.general.archive:
        path: /tmp/release
        dest: /tmp/release.tgz