---
- hosts: localhost
  vars:
    build_jobs: 16
    opensbi: "{{ starfive_visionfive2_opensbi }}"
    u_boot: "{{ starfive_visionfive2_u_boot }}"
    kernel: "{{ starfive_visionfive2_kernel }}"
  tasks:
    - include_tasks: tasks/build-kernel.yaml
    - include_tasks: tasks/copy-kernel-to-drive.yaml
