spacemit_kernel:
  git:
    # use own copy, the real repo is VERY slow!
    repo: "https://github.com/spacemit-com/linux-k1x.git"
    version: "k1"
    folder: "linux-k1x"
    checkout: true # set te true for clean checkout
  extra_firmware_download:
    - https://gitee.com/bianbu-linux/buildroot-ext/blob/bl-v2.0.y/board/spacemit/k1/target_overlay/lib/firmware/esos.elf
  target: "/home/opvolger/code/spacemit-kernel"
  dtb_file_location: /arch/riscv/boot/dts/spacemit/k1-x_milkv-jupiter.dtb
  defconfig: k1_defconfig
  # do not use modules
  replace_m_for_y: false
  build_params:
    CROSS_COMPILE: riscv64-linux-gnu-
    # CROSS_COMPILE: riscv64-unknown-linux-gnu-
    ARCH: riscv
  add_to_config:
    # disable signing check
    CONFIG_MODULE_SIG_KEY: ""

    # disable wifi (no firmwares)
    # platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
    CONFIG_WLAN: n
    CONFIG_WIRELESS: n

    # disable REMOTEPROC (give error)
    CONFIG_REMOTEPROC: n
    
    # disable onboard DRM/GPU
    CONFIG_DRM_SPACEMIT: n
    CONFIG_SPACEMIT_HDMI: n
    CONFIG_SPACEMIT_HDMIAUDIO: n

    # firmware in kernel
    CONFIG_EXTRA_FIRMWARE: "esos.elf radeon/CYPRESS_pfp.bin radeon/CYPRESS_me.bin radeon/CYPRESS_rlc.bin radeon/CYPRESS_smc.bin radeon/CYPRESS_uvd.bin"
    CONFIG_EXTRA_FIRMWARE_DIR: "../linux-firmware"

    CONFIG_842_COMPRESS: y
    CONFIG_842_DECOMPRESS: y
    CONFIG_LZ4_COMPRESS: y
    CONFIG_LZ4HC_COMPRESS: y
    CONFIG_LZ4_DECOMPRESS: y

    # AMDGPU + HDMI sound
    CONFIG_DRM_RADEON: y
    CONFIG_DRM_RADEON_USERPTR: n
    CONFIG_DRM_AMDGPU: y
    CONFIG_DRM_AMDGPU_SI: n
    CONFIG_DRM_AMDGPU_CIK: n
    CONFIG_DRM_AMDGPU_USERPTR: n
    CONFIG_DRM_AMD_ISP: n
    CONFIG_DRM_AMD_ACP: y
    CONFIG_DRM_AMD_DC: y
    CONFIG_DRM_AMD_DC_FP: y

    CONFIG_SND_DYNAMIC_MINORS: y
    CONFIG_SND_MAX_CARDS: 32
    CONFIG_SND_VMASTER: y

    CONFIG_SND_HDA: y
    CONFIG_SND_HDA_INTEL: y
    CONFIG_SND_HDA_HWDEP: n
    CONFIG_SND_HDA_RECONFIG: n
    CONFIG_SND_HDA_INPUT_BEEP: n
    CONFIG_SND_HDA_PATCH_LOADER: n
    CONFIG_SND_HDA_SCODEC_CS35L56_I2C: n
    CONFIG_SND_HDA_SCODEC_CS35L56_SPI: n
    CONFIG_SND_HDA_CODEC_REALTEK: n
    CONFIG_SND_HDA_CODEC_ANALOG: n
    CONFIG_SND_HDA_CODEC_SIGMATEL: n
    CONFIG_SND_HDA_CODEC_VIA: n
    CONFIG_SND_HDA_CODEC_HDMI: y
    CONFIG_SND_HDA_CODEC_CIRRUS: n
    CONFIG_SND_HDA_CODEC_CS8409: n
    CONFIG_SND_HDA_CODEC_CONEXANT: n
    CONFIG_SND_HDA_CODEC_SENARYTECH: n
    CONFIG_SND_HDA_CODEC_CA0110: n
    CONFIG_SND_HDA_CODEC_CA0132: n
    CONFIG_SND_HDA_CODEC_CMEDIA: n
    CONFIG_SND_HDA_CODEC_SI3054: n
    CONFIG_SND_HDA_GENERIC: n
    CONFIG_SND_HDA_POWER_SAVE_DEFAULT: 0
    CONFIG_SND_HDA_INTEL_HDMI_SILENT_STREAM: n
    CONFIG_SND_HDA_CTL_DEV_ID: n

    CONFIG_SND_HDA_CORE: y
    CONFIG_SND_HDA_COMPONENT: y
    CONFIG_SND_HDA_PREALLOC_SIZE: 64
    CONFIG_SND_INTEL_DSP_CONFIG: y

    # needed for ubuntu (snap):
    CONFIG_SQUASHFS: y
    CONFIG_SQUASHFS_FILE_CACHE: y


    # needed for Fedora (zram)
    CONFIG_ZSMALLOC: y
    CONFIG_ZSMALLOC_STAT: y
    CONFIG_ZSMALLOC_CHAIN_SIZE: 8
    CONFIG_ZRAM: y
    CONFIG_ZRAM_BACKEND_LZ4: y
    CONFIG_ZRAM_BACKEND_LZ4HC: y
    CONFIG_ZRAM_BACKEND_ZSTD: y
    CONFIG_ZRAM_BACKEND_DEFLATE: y
    CONFIG_ZRAM_BACKEND_842: y
    CONFIG_ZRAM_BACKEND_LZO: y
    CONFIG_ZRAM_DEF_COMP_LZ4: y
    CONFIG_ZRAM_DEF_COMP: "lz4"
    CONFIG_ZRAM_WRITEBACK: y
    CONFIG_ZRAM_TRACK_ENTRY_ACTIME: y
    CONFIG_ZRAM_MEMORY_TRACKING: y
    CONFIG_ZRAM_MULTI_COMP: y
    CONFIG_BLK_DEV_RAM: y
    CONFIG_BLK_DEV_RAM_COUNT: 16
    CONFIG_BLK_DEV_RAM_SIZE: 4096
    CONFIG_BTRFS_FS: y
