starfive_visionfive2_u_boot_ubuntu_24_10:
  git:
    repo: "https://github.com/u-boot/u-boot.git"
    version: "v2024.01"    
    checkout_dir: "/tmp/u-boot"
  file_patches:
    - files/u-boot-ubuntu/patches/allwinner/0001-arm-sunxi-Reduce-inrush-current-on-Olimex-A20-OLinuX.patch
    - files/u-boot-ubuntu/patches/arndale/board-spl-rule.diff
    - files/u-boot-ubuntu/patches/test-imagetools-test-fixes
    - files/u-boot-ubuntu/patches/exynos/0001-arm-config-fix-default-console-only-to-specify-the-d.patch
    - files/u-boot-ubuntu/patches/disable-fit-image-tests
    - files/u-boot-ubuntu/patches/rockchip/rockchip-inno-usb.patch
    - files/u-boot-ubuntu/patches/qemu/efi-secure-boot.patch
    - files/u-boot-ubuntu/patches/Makefile-Use-relative-paths-for-debugging-symbols.patch
    - files/u-boot-ubuntu/patches/riscv64/efi_loader-avoid-pointer-access-after-calling-efi_de.patch
    - files/u-boot-ubuntu/patches/riscv64/efi_loader-create-common-function-to-free-struct-efi.patch
    - files/u-boot-ubuntu/patches/riscv64/board-starfive-handle-compatible-property-in-dynamic.patch
    - files/u-boot-ubuntu/patches/riscv64/configs-visionfive2-Disable-ENV_IS_NOWHERE.patch
    - files/u-boot-ubuntu/patches/riscv64/serial-move-sbi_dbcn_available-to-.data-section.patch
    - files/u-boot-ubuntu/patches/riscv64/riscv-sifive-fu740-reduce-DDR-speed-from-1866MT-s-to-1600MT-s.patch
    - files/u-boot-ubuntu/patches/am62x/0008-arm-dts-k3-am625-Don-t-try-to-build-the-final-firmwa.patch
    - files/u-boot-ubuntu/patches/rpi-config-tweaks.patch
    - files/u-boot-ubuntu/patches/ubuntu-hardening-limit-keynames-to-keydir.patch
    - files/u-boot-ubuntu/patches/ubuntu-nitrogen6q2g-config-tweaks.patch
    - files/u-boot-ubuntu/patches/rpi-board-dt.patch
    - files/u-boot-ubuntu/patches/rpi-cm4-sdhci.patch
    - files/u-boot-ubuntu/patches/rpi-8gb-pci.patch
    - files/u-boot-ubuntu/patches/rpi-maxargs.patch
    - files/u-boot-ubuntu/patches/efivars-commands.patch
    - files/u-boot-ubuntu/patches/riscv64/enable-sbi.patch
    - files/u-boot-ubuntu/patches/riscv64/usb-reset.patch
    - files/u-boot-ubuntu/patches/riscv64/0001-eeprom-starfive-function-get_product_id_from_eeprom.patch
    - files/u-boot-ubuntu/patches/riscv64/0002-riscv-set-fdtfile-on-Milk-V-Mars.patch
    - files/u-boot-ubuntu/patches/riscv64/0003-board-starfive-support-Milk-V-Mars-board.patch
    - files/u-boot-ubuntu/patches/riscv64/0004-riscv-starfive-avoid-including-common.h.patch
    - files/u-boot-ubuntu/patches/riscv64/0005-doc-describe-Milk-V-Mars-board.patch
    - files/u-boot-ubuntu/patches/riscv64/0001-boot-enable-booting-via-EFI-boot-manager-by-default.patch
    - files/u-boot-ubuntu/patches/riscv64/0002-boot-correct-the-default-sequence-of-boot-methods.patch
    - files/u-boot-ubuntu/patches/riscv64/0003-efi_loader-move-HOST_ARCH-to-version_autogenerated.h.patch
    - files/u-boot-ubuntu/patches/riscv64/0004-boot-correct-finding-the-default-EFI-binary.patch
    - files/u-boot-ubuntu/patches/use-cpp-flags.patch
    - files/u-boot-ubuntu/patches/rpi-fit-images.patch
    - files/u-boot-ubuntu/patches/riscv64/synopsys-designware-cd-gpios.patch
    - files/u-boot-ubuntu/patches/riscv64/starfive-mmc-card-detect.patch
    - files/u-boot-ubuntu/patches/riscv64/erase-env.patch
  defconfig: starfive_visionfive2_defconfig
  add_to_config:
    # disable nvme in u-boot (some GPU don't like that)
    CONFIG_PCI_INIT_R: n
    CONFIG_CMD_PCI: n

    # https://launchpad.net/ubuntu/+source/u-boot/2024.01+dfsg-5ubuntu2
    # https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/u-boot/2024.01+dfsg-5ubuntu2/u-boot_2024.01+dfsg-5ubuntu2.debian.tar.xz
    # see files

  build_params:
    OPENSBI: ../opensbi/build/platform/generic/firmware/fw_payload.bin
    CONFIG_DEFAULT_FDT_FILE: starfive/jh7110-starfive-visionfive-2-v1.3b.dtb
    CROSS_COMPILE: riscv64-linux-gnu-

