- name: Git checkout u-boot
  ansible.builtin.git:
    repo: '{{ u_boot.git.repo }}'
    dest: '{{ u_boot.git.checkout_dir }}'
    force: true
    version: '{{ u_boot.git.version }}'

- name: Build distclean
  community.general.make:
    make: make
    chdir: '{{ u_boot.git.checkout_dir }}'
    target: distclean

- name: Delete untracked files from the working tree
  ansible.builtin.shell: 
    cmd: git clean -f
    chdir: '{{ u_boot.git.checkout_dir }}'


- name: Patches (http)
  block:
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /tmp/{{ item | basename }}
    loop: "{{ u_boot.file_patches }}"

  - name: Apply patch {{ item | basename }}
    ansible.builtin.shell: 
      cmd: git apply /tmp/{{ item | basename }}
      chdir: '{{ u_boot.git.checkout_dir }}'
    loop: "{{ u_boot.file_patches }}"
  when: u_boot.file_patches is defined



- name: Patches (http)
  block:
  - name: Download {{ item }}
    ansible.builtin.get_url:
      url: "{{ item }}"
      dest: "/tmp/{{ item | basename }}"
    loop: "{{ u_boot.https_patches }}"

  - name: Apply patch {{ item | basename }}
    ansible.builtin.shell: 
      cmd: git apply /tmp/{{ item | basename }}
      chdir: '{{ u_boot.git.checkout_dir }}'
    loop: "{{ u_boot.https_patches }}"
  when: u_boot.https_patches is defined

- name: Add to configfile {{ u_boot.git.checkout_dir }}/configs/{{ u_boot.defconfig }}
  ansible.builtin.shell: echo "{{ item.key }}={{ item.value }}" >> {{ u_boot.git.checkout_dir }}/configs/{{ u_boot.defconfig }}
  when: 
    - item.value |string | length < 5 
  loop: "{{ lookup('ansible.builtin.dict', u_boot.add_to_config) }}"

- name: Add to configfile string {{ u_boot.git.checkout_dir }}/configs/{{ u_boot.defconfig }}
  ansible.builtin.shell: echo '{{ item.key }}="{{ item.value }}"' >> {{ u_boot.git.checkout_dir }}/configs/{{ u_boot.defconfig }}
  when: 
    - item.value |string | length > 5 
  loop: "{{ lookup('ansible.builtin.dict', u_boot.add_to_config) }}"

- name: Build .config
  community.general.make:
    make: make
    chdir: '{{ u_boot.git.checkout_dir }}'
    target: '{{ u_boot.defconfig }}'

- name: Build u-boot
  community.general.make:
    make: make
    chdir: '{{ u_boot.git.checkout_dir }}'
    jobs: '{{ build_jobs }}'
    params: '{{ u_boot.build_params }}'
